---
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    networks:
      - media
    ports:
      - 8989:8989
    volumes:
      - /home/$USER/config/sonarr:/config
      - /mnt/media/TV Shows:/tv
      - /mnt/media/Downloads :/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    networks:
      - media
    ports:
      - "7878:7878"
    volumes:
      - /home/$USER/config/sonarr:/config
      - /mnt/media/Movies:/movies
      - /mnt/media/Downloads :/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich

  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DOCKER_MODS=linuxserver/mods:universal-calibre
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - /home/$USER/config/calibre-web:/config
      - /mnt/media/Books/Calibre/library:/books
    ports:
      - 8083:80
    restart: unless-stopped

networks:
  media:
    driver: bridge
