services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    networks:
      - media
    ports:
      - "8989:8989"
    volumes:
      - ./config/sonarr:/config
      - /path/to/media:/media
      - /path/to/downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    networks:
      - media
    ports:
      - "7878:7878"
    volumes:
      - ./config/radarr:/config
      - /path/to/media:/media
      - /path/to/downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich

networks:
  media:
    driver: bridge
